const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();}
let state=null, filter='all';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const icon=n=>({"Ржавый меч":"⚔️","Дубина":"🔨","Лук":"🏹","Копьё":"🔱","Топор":"🪓","Молот":"🔨","Магический посох":"🪄","Кожаный шлем":"🪖","Кожаный доспех":"🦺","Кожаные штаны":"👖","Деревянный щит":"🛡️","Кольчужный шлем":"🪖","Кольчужный нагрудник":"🛡️","Кольчужные латы":"👖","Стальной шлем":"🪖","Стальной нагрудник":"🛡️","Стальные поножи":"👖","Стальной щит":"🛡️","Эбонитовый шлем":"🪖","Эбонитовый нагрудник":"🛡️","Эбонитовые латы":"👖","Эбонитовый щит":"🛡️","Медное кольцо":"💍","Значок храбрости":"🏅","Значок воли":"🏅","Значок скорости":"🏅","За отличную службу":"🏅","Малое зелье лечения":"🧪","Большое зелье лечения":"🧪","Зелье бодрости":"⚡","Хлеб":"🍞","Каша":"🥣","Похлёбка":"🍲","Вяленое мясо":"🥩","Рыба":"🐟","Пиво":"🍺","Эль":"🍻","Сидр":"🥂","Гуляющая Устрица":"🍜","Грибной суп":"🍄","Слизь":"🟢","Хвост крысы":"🐀","Ухо гоблина":"👂","Вороний клюв":"🐦","Воронье перо":"🪶","Гриб":"🍄","Медная руда":"🪨","Железная руда":"⛏️","Эбонитовая руда":"⬛"}[n]||'📦');
function initData(){return tg?.initData||''}
async function api(url,opt={}){const o={...opt,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData(),...(opt.headers||{})}};const r=await fetch(url,o);const d=await r.json();if(!r.ok)throw Error(d.error||'Ошибка сервера');return d}
async function load(){try{state=await api('/api/inventory');render()}catch(e){show(e.message)}}
function render(){
 const u=state.user; $('#playerCard').classList.remove('skeleton');$('#playerCard').innerHTML=`<div class="player-main"><div><div class="name">${esc(u.name)}</div><div class="race">${esc(u.race||'Без расы')} · этаж ${u.floor}</div></div><div class="pill">🪙 ${u.gold}</div></div><div class="resources"><div class="pill">❤️ ${u.hp}/${u.max_hp}</div><div class="pill">⚡ ${u.energy}/${u.max_energy}</div><div class="pill">💠 ${u.quanta}</div></div><div class="stats"><div class="stat"><b>${u.str}</b><span>Сила</span></div><div class="stat"><b>${u.end}</b><span>Выносливость</span></div><div class="stat"><b>${u.agi}</b><span>Ловкость</span></div></div>`;
 const labels={weapon:'⚔ Оружие',helmet:'🪖 Шлем',chest:'🦺 Нагрудник',legs:'👖 Штаны',shield:'🛡 Щит',ring:'💍 Кольцо',badge:'🏅 Значок'};$('#equipmentGrid').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="equip"><div class="equip-label">${l}</div><div class="equip-name">${esc(u.equip[k]||'—')}</div></div>`).join('');
 $('#slots').textContent=`${u.slots_used}/${u.inv_size} слотов`;renderFilters();renderItems();
}
function renderFilters(){const fs=[['all','Все'],['potion','Зелья'],['weapon','Оружие'],['armor','Броня'],['food','Еда'],['material','Материалы'],['other','Прочее']];$('#filters').innerHTML=fs.map(([k,n])=>`<button class="filter ${filter===k?'active':''}" data-filter="${k}">${n}</button>`).join('');document.querySelectorAll('.filter').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;renderFilters();renderItems()})}
function renderItems(){let items=state.items;if(filter!=='all')items=items.filter(x=>x.category===filter);$('#items').innerHTML=items.length?items.map((x,i)=>`<div class="item" data-i="${state.items.indexOf(x)}"><div class="item-icon">${icon(x.name)}</div><div class="item-name">${esc(x.name)}</div><div class="item-count">×${x.count}</div></div>`).join(''):'<div class="empty">В этой категории пусто</div>';document.querySelectorAll('.item').forEach(x=>x.onclick=()=>openItem(state.items[+x.dataset.i]))}
function openItem(x){let actions='';if(x.action==='equip'||x.action==='use'||x.action==='sell')actions+=`<button class="action primary" onclick="doAction('${encodeURIComponent(x.name)}','use')">${esc(x.action_label)}</button>`;actions+=`<button class="action danger" onclick="doAction('${encodeURIComponent(x.name)}','drop')">🗑 Выбросить 1</button>`;if(x.count>1)actions+=`<button class="action danger" onclick="doAction('${encodeURIComponent(x.name)}','drop_all')">🗑 Выбросить всё</button>`;$('#modalContent').innerHTML=`<div class="modal-icon">${icon(x.name)}</div><h2>${esc(x.name)}</h2><div class="desc">Количество: ${x.count}<br>${esc(x.description||'Предмет из инвентаря Eternal Tower.')}</div><div class="actions">${actions}</div>`;$('#modal').classList.remove('hidden')}
window.doAction=async(name,action)=>{try{const d=await api('/api/item/action',{method:'POST',body:JSON.stringify({name:decodeURIComponent(name),action})});state=d;closeModal();render();show('Готово');}catch(e){show(e.message)}};
function closeModal(){$('#modal').classList.add('hidden')};function show(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
$('#closeModal').onclick=closeModal;$('.modal-backdrop').onclick=closeModal;$('#refreshBtn').onclick=load;load();
